name: flutter_mux_live
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_stream: ^0.0.1
  video_player: ^2.3.0
  wakelock: ^0.6.1+2
  firebase_core: ^1.13.1
  cloud_functions: ^3.2.10
  intl: ^0.17.0
  font_awesome_flutter: ^9.2.0
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Regular.ttf
        - asset: fonts/GoogleSans-Medium.ttf
        - asset: fonts/GoogleSans-Bold.ttf
