// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGY1OV9LpnHApQPqSZSWUz3mCtLHUdUd0',
    appId: '1:7086588376:web:736c2006585a613757b2ad',
    messagingSenderId: '7086588376',
    projectId: 'live-stream-31a10',
    authDomain: 'live-stream-31a10.firebaseapp.com',
    storageBucket: 'live-stream-31a10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApKTQsO9iWHtJnbXyGGxgIpN0Slxm3m2w',
    appId: '1:7086588376:android:5825deda09e1ae6157b2ad',
    messagingSenderId: '7086588376',
    projectId: 'live-stream-31a10',
    storageBucket: 'live-stream-31a10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsQH05iso_zVqs95wMQ5BoSBby0u5x6rE',
    appId: '1:7086588376:ios:e2c1a205109927e657b2ad',
    messagingSenderId: '7086588376',
    projectId: 'live-stream-31a10',
    storageBucket: 'live-stream-31a10.appspot.com',
    iosClientId: '7086588376-aobp8cvaer1lj4jj9j07slug5kn35f9b.apps.googleusercontent.com',
    iosBundleId: 'io.flutterflow.flutterMuxLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsQH05iso_zVqs95wMQ5BoSBby0u5x6rE',
    appId: '1:7086588376:ios:e2c1a205109927e657b2ad',
    messagingSenderId: '7086588376',
    projectId: 'live-stream-31a10',
    storageBucket: 'live-stream-31a10.appspot.com',
    iosClientId: '7086588376-aobp8cvaer1lj4jj9j07slug5kn35f9b.apps.googleusercontent.com',
    iosBundleId: 'io.flutterflow.flutterMuxLive',
  );
}
